### ISSUE TITLE
qc-bvec not outputing into the right directory

### ISSUE THREAD

**Issue by navonacalarco** [josephdviviano/qcmon#1]
it's outputing into the same directory as the input file

**Comment by josephdviviano** [comment]
Can you post the full command?

**Comment by josephdviviano** [comment]
I think you must be making a mistake, this worked for me:

```
jviviano@nissl:~/test/SPN01_CMH_0001_01$ qc-bvecs  SPN01_CMH_0001_01/SPN01_CMH_0001_01_01_DTI60-1000_20_Ax-DTI-60plus5.bvec SPN01_CMH_0001_01/SPN01_CMH_0001_01_01_DTI60-1000_20_Ax-DTI-60plus5.bval SPN01_CMH_0001_01/test.csv
```

**Comment by josephdviviano** [comment]
Oh wait, I see the issue. The image will not be output to the correct directory.

**Comment by josephdviviano** [comment]
Fixed. See https://github.com/josephdviviano/qcmon/commit/35f231be1df336eae1ba7c9318c2dbe1a6fc131f
