### ISSUE TITLE
the new MRP (prisma) IMI causes a bug for sfnr

### ISSUE THREAD

**Issue by navonacalarco** [josephdviviano/qcmon#2]
The EA and RST scans from the same session qcmoned just fine.

But the sfnr img for IMI is empty (all zeros)

Python error was:
/projects/navona/Kimel_lab/code/qcmon/bin/qc-fmri:80: RuntimeWarning: invalid value encountered in divide
  func = func / np.tile(np.linalg.norm(func, ord=2, axis=1), (dims[1], 1)).T # l2 norm

**Comment by josephdviviano** [comment]
Can you post the full command

**Comment by josephdviviano** [comment]
@navonacalarco

**Comment by josephdviviano** [comment]
I think you must mean the `corr` image, not the `sfnr`. I can generate it OK...

Looking into the correlation calculation now.

**Comment by josephdviviano** [comment]
Replaced instances in norm where you encounter a 0 with a very small number, resolves bug.
